site_name: Causal Consistency NN
nav:
  - Home: index.md
  - Training: training.md
  - Pyro SVI Training: pyro_training.md
  - Serving: serving.md
  - Evaluation Metrics: metrics.md
  - Model Card: model_card.md
  - Configuration: configuration.md
  - API Reference: api.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
