name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        hardware: [cpu, cuda]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff pytest
      - name: Run formatters
        run: |
          black .
          ruff check --fix .
      - name: Commit formatting changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git commit -am "chore: apply style fixes"
            git push
          fi
      - name: Run tests
        run: pytest -s